version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: America/Toronto
    reviewers:
      - "jonathansick"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: America/Toronto
    # Generally this means we'll get minor and patch updates, but we'll
    # manually need to roll out major version changes.
    versioning-strategy: "lockfile-only"
    registries:
      - npm-github
    reviewers:
      - "jonathansick"
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    # lsst-sqre org secret (for Dependabot)
    token: ${{ secrets.READONLY_PACKAGES_GITHUB_TOKEN }}
