siteName: 'Times Square'
baseUrl: 'http://localhost:3000'
siteDescription: |
  The site description.
semaphoreUrl: 'https://data-dev.lsst.cloud/semaphore'
timesSquareApiUrl: 'http://localhost:3000/api/times-square'
